# Generated by Django 2.1.3 on 2018-12-03 07:53

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.TextField()),
                ('Author', models.CharField(max_length=50)),
                ('Date', django_jalali.db.models.jDateField()),
                ('Time', models.TimeField()),
                ('Email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField()),
                ('Type', models.CharField(max_length=50)),
                ('SubTitle', models.TextField()),
                ('About', models.TextField()),
                ('Author', models.CharField(max_length=50)),
                ('Avatar', models.ImageField(upload_to='static/image/avatar/')),
                ('Text', ckeditor.fields.RichTextField()),
                ('Date', django_jalali.db.models.jDateField()),
                ('AparatLink', models.TextField()),
                ('PostImage', models.ImageField(upload_to='static/image/post/')),
            ],
        ),
        migrations.AddField(
            model_name='like',
            name='RelPost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='RelPost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Post'),
        ),
    ]
