# Generated by Django 2.1.3 on 2018-12-03 08:22

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='About',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='AparatLink',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='Author',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='Avatar',
            field=models.ImageField(null=True, upload_to='static/image/avatar/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='PostImage',
            field=models.ImageField(null=True, upload_to='static/image/post/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='SubTitle',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='Text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
