# Generated by Django 2.1.3 on 2018-12-03 08:28

from django.db import migrations
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20181203_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Text',
            field=redactor.fields.RedactorField(verbose_name='Краткий текст'),
        ),
    ]
