# Generated by Django 2.1.3 on 2018-12-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20181203_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Text',
            field=models.TextField(),
        ),
    ]
