# Generated by Django 2.1.3 on 2018-12-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20181203_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Avatar',
            field=models.ImageField(blank=True, null=True, upload_to='static/image/avatar/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='PostImage',
            field=models.ImageField(blank=True, null=True, upload_to='static/image/post/'),
        ),
    ]
