# Generated by Django 2.1.3 on 2018-12-03 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20181203_0840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PostLink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Post')),
            ],
        ),
    ]
