# Generated by Django 2.1.3 on 2018-12-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20181203_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
