# Generated by Django 2.1.3 on 2018-12-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Category',
            field=models.CharField(max_length=50),
        ),
    ]
