# Generated by Django 2.1.3 on 2018-12-07 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20181203_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='PostLink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner', to='web.Post'),
        ),
    ]
