# Generated by Django 2.1.3 on 2018-12-07 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20181207_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='Time',
        ),
        migrations.AddField(
            model_name='comment',
            name='Valid',
            field=models.BooleanField(default=False),
        ),
    ]
