# Generated by Django 2.1.3 on 2018-12-08 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('web', '0011_auto_20181207_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='Author',
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.Session'),
        ),
    ]
