# Generated by Django 2.1.3 on 2018-12-16 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20181216_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatedpost',
            name='MainPost',
        ),
        migrations.RemoveField(
            model_name='relatedpost',
            name='related',
        ),
        migrations.DeleteModel(
            name='RelatedPost',
        ),
    ]
